### ISSUE TITLE
Error using  Cognito.register

### ISSUE THREAD

**Issue by vanerleo** [bagubits/angular-aws#1]
I'm getting "Cannot read property 'push' of undefined"  in  `Cognito.register` on line 57 
`this.cognitoAttributeList.push(userAttribute);`

`this.cognitoAttributeList` seems undefined ... 

i've injected `Cognito` into a factory, as per usual

**Comment by neerajkumarnj** [comment]
Make sure you are using init function to initialize your cognito object before registering
